/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/yNXYnx12ntU
 */
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { SheetTrigger, SheetContent, Sheet } from "@/components/ui/sheet"
import { CardTitle, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"

export function HackerDashboard() {
  return (
    <div key="1" className="flex min-h-screen w-full flex-col">
      <header className="sticky top-0 flex h-16 items-center gap-4 border-b bg-background px-4 md:px-6">
        <nav className="hidden flex-col gap-6 text-lg font-medium md:flex md:flex-row md:items-center md:gap-5 md:text-sm lg:gap-6">
          <Link className="flex items-center gap-2 text-lg font-semibold md:text-base" href="#">
            <Package2Icon className="h-6 w-6" />
            <span className="sr-only">Acme Inc</span>
          </Link>
          <Link className="text-muted-foreground transition-colors hover:text-foreground" href="#">
            Home
          </Link>
          <Link className="text-muted-foreground transition-colors hover:text-foreground" href="#">
            Announcements
          </Link>
          <Link className="text-muted-foreground transition-colors hover:text-foreground" href="#">
            Schedule
          </Link>
          <Link className="text-muted-foreground transition-colors hover:text-foreground" href="#">
            FAQ
          </Link>
          <Link className="text-muted-foreground transition-colors hover:text-foreground" href="#">
            Challenges
          </Link>
          <Link className="text-muted-foreground transition-colors hover:text-foreground" href="#">
            Sponsors
          </Link>
          <Link className="text-muted-foreground transition-colors hover:text-foreground" href="#">
            My Hacker ID
          </Link>
          <Link className="text-muted-foreground transition-colors hover:text-foreground" href="#">
            Apply
          </Link>
          <Link className="text-foreground transition-colors hover:text-foreground" href="#">
            Logout
          </Link>
        </nav>
        <Sheet>
          <SheetTrigger asChild>
            <Button className="shrink-0 md:hidden" size="icon" variant="outline">
              <MenuIcon className="h-6 w-6" />
              <span className="sr-only">Toggle navigation menu</span>
            </Button>
          </SheetTrigger>
          <SheetContent side="left">
            <Link href="#">
              <Package2Icon className="h-6 w-6" />
              <span className="sr-only">Acme Inc</span>
            </Link>
            <div className="grid gap-2 py-6">
              <Link className="flex w-full items-center py-2 text-lg font-semibold" href="#">
                General
              </Link>
              <Link className="flex w-full items-center py-2 text-lg font-semibold" href="#">
                Hackathon Experience
              </Link>
              <Link className="flex w-full items-center py-2 text-lg font-semibold" href="#">
                Event Info
              </Link>
              <Link className="flex w-full items-center py-2 text-lg font-semibold" href="#">
                Profile Info
              </Link>
            </div>
          </SheetContent>
        </Sheet>
      </header>
      <main className="flex-1 flex">
        <nav className="hidden md:flex flex-col w-64 bg-gray-100 dark:bg-gray-800">
          <Link className="py-4 px-6 text-lg font-semibold border-b border-gray-200 dark:border-gray-700" href="#">
            General
          </Link>
          <Link className="py-4 px-6 text-lg font-semibold border-b border-gray-200 dark:border-gray-700" href="#">
            Hackathon Experience
          </Link>
          <Link className="py-4 px-6 text-lg font-semibold border-b border-gray-200 dark:border-gray-700" href="#">
            Event Info
          </Link>
          <Link className="py-4 px-6 text-lg font-semibold border-b border-gray-200 dark:border-gray-700" href="#">
            Profile Info
          </Link>
        </nav>
        <section className="w-full py-8 px-4 md:px-6" id="general">
          <CardContent>
            <Card className="w-full max-w-md mx-auto p-4 my-4">
              <CardHeader>
                <CardTitle>Personal Information</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="grid grid-cols-1 gap-4 mt-4">
                  <div className="space-y-2">
                    <Label htmlFor="first-name">First Name</Label>
                    <Input id="first-name" placeholder="Enter your first name" required />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="last-name">Last Name</Label>
                    <Input id="last-name" placeholder="Enter your last name" required />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="email">Email</Label>
                    <Input id="email" placeholder="Enter your email" required type="email" />
                  </div>
                </div>
              </CardContent>
              <CardFooter>
                <Button>Save Personal Information</Button>
              </CardFooter>
            </Card>
            <Card className="w-full max-w-md mx-auto p-4 my-4">
              <CardHeader>
                <CardTitle>Demographic Information</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="grid grid-cols-1 gap-4 mt-4">
                  <div className="space-y-2">
                    <Label htmlFor="age">Age</Label>
                    <Input id="age" placeholder="Enter your age" required type="number" />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="race">Race</Label>
                    <Input id="race" placeholder="Enter your race" required />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="gender">Gender</Label>
                    <Input id="gender" placeholder="Enter your gender" required />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="ethnicity">Ethnicity</Label>
                    <Input id="ethnicity" placeholder="Enter your ethnicity" required />
                  </div>
                </div>
              </CardContent>
              <CardFooter>
                <Button>Save Demographic Information</Button>
              </CardFooter>
            </Card>
            <Card className="w-full max-w-md mx-auto p-4 my-4">
              <CardHeader>
                <CardTitle>Education Information</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="grid grid-cols-1 gap-4 mt-4">
                  <div className="space-y-2">
                    <Label htmlFor="university">University</Label>
                    <Input id="university" placeholder="Enter your university" required />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="major">Major</Label>
                    <Input id="major" placeholder="Enter your major" required />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="study-level">Study Level</Label>
                    <Input id="study-level" placeholder="Enter your study level" required />
                  </div>
                </div>
              </CardContent>
              <CardFooter>
                <Button>Save Education Information</Button>
              </CardFooter>
            </Card>
          </CardContent>
        </section>
      </main>
    </div>
  )
}


function Package2Icon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 9h18v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V9Z" />
      <path d="m3 9 2.45-4.9A2 2 0 0 1 7.24 3h9.52a2 2 0 0 1 1.8 1.1L21 9" />
      <path d="M12 3v6" />
    </svg>
  )
}


function MenuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  )
}
